disabled_rules:
  - valid_docs
  - conditional_binding_cascade

included:

excluded:
  - Carthage
  - Pods

# Overrides

line_length: 175

type_name:
  min_length: 4
  max_length: 50
function_parameter_count: 10
